### ISSUE TITLE
Error: "This method only supports Buffer but input was..." on ARM based Mac M1

### ISSUE THREAD

**Issue by itinance** [OpenZeppelin/openzeppelin-contracts#2880] opened 2021-09-23 07:34 UTC
Running the test suite will cause an important warning and an error on Mac M1, which both won't happen on Intel-based Mac:

1. The Warning of exceedes code size:

```
Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
 --> contracts/mocks/GovernorCompatibilityBravoMock.sol:9:1:
  |
9 | contract GovernorCompatibilityBravoMock is GovernorCompatibilityBravo, GovernorTimelockCompound, GovernorVotesComp {
  | ^ (Relevant source part starts here and spans across multiple lines).
```

2. The Error:

```
Compilation finished successfully
An unexpected error occurred:

Error: This method only supports Buffer but input was: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    at Object.exports.assertIsBuffer (/private/tmp/openzeppelin-contracts/node_modules/ethereumjs-util/src/helpers.ts:21:11)
    at Object.exports.privateToPublic (/private/tmp/openzeppelin-contracts/node_modules/ethereumjs-util/src/account.ts:275:3)
    at exports.privateToAddress (/private/tmp/openzeppelin-contracts/node_modules/ethereumjs-util/src/account.ts:285:26)
    at /private/tmp/openzeppelin-contracts/node_modules/@nomiclabs/hardhat-truffle5/src/index.ts:140:41
    at Array.map (<anonymous>)
    at describeContract (/private/tmp/openzeppelin-contracts/node_modules/@nomiclabs/hardhat-truffle5/src/index.ts:139:11)
    at /private/tmp/openzeppelin-contracts/node_modules/@nomiclabs/hardhat-truffle5/src/index.ts:162:20
    at env.contract (/private/tmp/openzeppelin-contracts/hardhat/env-contract.js:8:5)
    at Object.<anonymous> (/private/tmp/openzeppelin-contracts/test/access/AccessControl.test.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at /private/tmp/openzeppelin-contracts/node_modules/mocha/lib/mocha.js:349:36
er
```

**💻 Environment**

MacBook Pro M1 (ARM) with 16 GB RAM
MacOS BigSur 11.4

Node: tested with several versions:
- 16.7.0
- 15.4.0
- 14.17.5
- 12.22.5

**📝 Details**

```
git clone git@github.com:OpenZeppelin/openzeppelin-contracts.git
cd openzeppelin-contracts
npm install
npm run test
```

Importantly, on Intel-based Macs, this error does not occur, no matter which of the Node versions listed above I tested with.

**🔢 Code to reproduce bug**

no code changes made here, just used master branch

**Comment by Amxx** [comment] 2021-09-23 08:34
Hello @itinance 

The first issue is known: Tests are running without optimization for easier debugging, and this contract is too large to deploy unless optimizations are enabled. It is not a serious issue (people should always deploy an optimized version) and is not related to your particular environment.

I do not have a Mac machine to reproduce your second issue, but it looks like it's outside our scope. `openzeppelin-contracts/test/access/AccessControl.test.js:7:1` is the first "describe" in the first test file that is running ... and error looks like it originates from somewhere in `hardhat-truffle5` or `ethereumjs-utils`. I'd love to know more, but it is likely there is a more serious issue between your ARM based machine and one of these packages. 

Have you been able to run any truffle-based tests from another project? What about waffle/ethers? (migrating to that would require tremendous work though)

**Comment by itinance** [comment] 2021-09-23 09:26
Hi @Amxx, I had also `ethereum-utils` or `hardhat-truffle` already in my mind and try to figure out, if I can get more informations (and probably get in contact with them then). I will keep you guys updated here in this thread.

**Comment by swaylock** [comment] 2021-09-24 18:48
@itinance I'm also seeing this. There's an issue over on Hardhat that is tracking this as well:

https://github.com/nomiclabs/hardhat/issues/1885

Your report that this bug doesn't occur on Intel based Macs is worrying indeed.

**Comment by itinance** [comment] 2021-09-25 10:22
I can report that this issue seems to be solved right now.

Since I kept the older folder of "git clone"-output of openzeppelin I could check the difference between the state when this issue was happening and the state of today:

`/usr/bin/diff /tmp/openzeppelin-contracts/package.json /tmp/o/openzeppelin-contracts/package.json`

```
53c53
<     "@nomiclabs/hardhat-truffle5": "^2.0.1",
---
>     "@nomiclabs/hardhat-truffle5": "^2.0.0",
70c70
<     "hardhat": "^2.6.4",
---
>     "hardhat": "^2.0.6",
72c72
72c72
<     "keccak256": "^1.0.3",
---
>     "keccak256": "^1.0.2",
75,78c75,78
<     "merkletreejs": "^0.2.24",
<     "micromatch": "^4.0.4",
<     "prettier": "^2.4.1",
<     "prettier-plugin-solidity": "^1.0.0-beta.18",
---
>     "merkletreejs": "^0.2.13",
>     "micromatch": "^4.0.2",
>     "prettier": "^2.3.0",
>     "prettier-plugin-solidity": "^1.0.0-beta.16",
81,85c81,85
<     "solidity-ast": "^0.4.26",
<     "solidity-coverage": "^0.7.17",
<     "solidity-docgen": "^0.5.14",
<     "web3": "^1.5.3",
<     "yargs": "^17.2.0"
---
>     "solidity-ast": "^0.4.25",
>     "solidity-coverage": "^0.7.11",
>     "solidity-docgen": "^0.5.3",
>     "web3": "^1.3.0",
>     "yargs": "^16.2.0"
```

(I left out all lines that belongs to unit testing and linting here)

I was running successfully 

```
git clone git@github.com:OpenZeppelin/openzeppelin-contracts.git
cd openzeppelin-contracts
npm install
npm run test
```

both on Intel based Macs (where this issue never appeared for me) and ARM based Mac M1, where this issue was happening reproducable.

**Comment by Amxx** [comment] 2021-09-30 15:05
Experiencing that on x86-64 archlinux ...
Hopefully I find a fix in what you previously experimented

**Comment by frangio** [comment] 2021-10-06 19:43
This was an issue in Hardhat that was fixed on a recent release.

**Closed by frangio** 2021-10-06 19:43 UTC
