### ISSUE TITLE
Remove _setBaseURI from Initialize

### ISSUE THREAD

**Issue by EvilJordan** [OpenZeppelin/openzeppelin-contracts#2278] opened 2020-06-14 05:27 UTC
**🧐 Motivation**
The Upgradeable presets are amazing. Thank you so much!
However, one item in particular when it comes to ERC721s is the `tokenURI` and its **lack** of change-ability.  

**📝 Details**
Move the `_setBaseURI` method away from inside the `initialize` method, and into its own `public virtual` method, with a check for the `MINTER_ROLE`.

This would mean a new token would need to have `setBaseURI` called separately from the `initialize` method (👎 ), but it would allow for future changes (👍 ) if so desired.

**Comment by abcoathup** [comment] 2020-06-15 11:06
Hi @EvilJordan,

Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by abcoathup** [comment] 2020-06-15 11:10
My thoughts are that to allow for future changes, developers wanting to use `baseURI` for automatic token URI generation can either use a URI that they control such as `https://mydomain.com/api/token/` which can be pointed to the implementation of their choice or they can add a mechanism in the smart contract (with appropriate access control) to allow changing it.  This may or may not be the `MINTER_ROLE`.

In the two ERC721's I have been involved in, one was designed to use a domain approach, the other had a function with access control to change the base URI.

Please note that `baseURI` can be set in the constructor/initializer or it can be set to an empty string `""`.  OpenZeppelin Contracts Ethereum Package (upgradeable version) is generated from OpenZeppelin Contracts.

**Comment by EvilJordan** [comment] 2020-06-15 16:47
>one was designed to use a domain approach

This means a redirect on the domain side, correct? If so, while convenient, I think that puts a lot of trust in DNS. What happens if Project X gets bought by Project Y? I would, personally, like to rebrand everything to Project Y, and that would include a divestment of all Project X references.

>a function with access control to change the base URI

I think this is what I'm proposing, but it's currently not possible with the upgradeable preset... one can't override the `_baseURI` state because it's private to the inherited token contract.

**Comment by abcoathup** [comment] 2020-06-16 04:53
Hi @EvilJordan,

We can inherit from the preset contract and call `_setBaseURI`.

Using the OpenZeppelin Contracts Ethereum Package version it could look like the following:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

import "@openzeppelin/contracts-ethereum-package/contracts/Initializable.sol";
import "@openzeppelin/contracts-ethereum-package/contracts/presets/ERC721PresetMinterPauserAutoId.sol";

contract MyNFT is Initializable, ERC721PresetMinterPauserAutoIdUpgradeSafe {
    bytes32 public constant BASEURI_CHANGER_ROLE = keccak256(
        "BASEURI_CHANGER_ROLE"
    );

    function initialize() public initializer {
        __ERC721PresetMinterPauserAutoId_init("My NFT", "NFT", "https://example.com/api/token/");

        _setupRole(BASEURI_CHANGER_ROLE, _msgSender());
    }

    function changeBaseURI(string memory baseURI) public {
        require(
            hasRole(BASEURI_CHANGER_ROLE, _msgSender()),
            "MyNFT: must have baseuri changer role to change"
        );

        _setBaseURI(baseURI);
    }
}
```

It is whether functionality (including a role) should be included in the preset contract or whether the preset doesn't need to include this and the community can add this if required.

**Comment by EvilJordan** [comment] 2020-06-16 18:19
You are totally right, @abcoathup. Also, this code sample works perfectly. Thank you so much for all you do!!!

I'll leave this open for you to close if you feel like it.

**Comment by nventuro** [comment] 2020-06-16 20:02
Hello @EvilJordan, thanks for suggesting this!

The Presets are meant to be usable as-is and ready to deploy to mainnet, but they naturally don't cover for all possible use cases. The idea is to provide a working initial version that can be extended by users to develop their custom solution (like @abcoathup showed in the comment above).

We often say that Contracts' code should not be copy-pasted, and Presets might be the only exception. If you find you want to be able to change the base URI, but also have different roles for pausing and pausing, the sensible thing to do is to grab the Preset's code and modify it to suit your particular use-case. In that sense, they are also acting as a sort of example of how to put different modules together.

Hope that helps! I'm closing the issue since we won't be alterting the Preset's code.

**Closed by nventuro** 2020-06-16 20:02 UTC
