### ISSUE TITLE
Enable `supportsInterface(...)` from ERC165 on ERC20 contract implementation

### ISSUE THREAD

**Issue by CJ42** [OpenZeppelin/openzeppelin-contracts#3575] opened 2022-07-25 07:49 UTC
**🧐 Motivation**

In the current token implementations of OpenZeppelin contracts, [only the ERC721 implementation contains the `supportsInterface(...)` function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d1b1e17d23cc28eecd07e411a461854988803aa8/contracts/token/ERC721/ERC721.sol#L52).

ERC20 does not contain `supportsInterface(...)` by default.

I am not sure why this is the case, but my first guess would be the order that each of these ERC20 came up?
> Looking at [ERC721](https://eips.ethereum.org/EIPS/eip-721#specification) specs, ERC165 is mentioned but not in the formal [ERC20](https://eips.ethereum.org/EIPS/eip-20) specs.

**📝 Details**

Would it make sense to add `supportsInterface(...)` in ERC20, and make the contract inherit from `ERC165` as well? So that by default, both fungible and non-fungible tokens implementation from OZ library can be detected easily via this function?

Let me know your thoughts @frangio @Amxx and I would be happy to make a brief PR if this feature request is accepted.

**Comment by Amxx** [comment] 2022-07-25 08:47
Hello @CJ42 

As you point out:
> Looking at [ERC721](https://eips.ethereum.org/EIPS/eip-721#specification) specs, ERC165 is mentioned but not in the formal [ERC20](https://eips.ethereum.org/EIPS/eip-20) specs.

ERC721's interfaceId is widely known, and expected in all ERC721 implementation. You can therefore rely on it to check it an unknown contract is ERC721

ERC20's interfaceId is not widelly accepted, ERC20 is not required to implement ERC165, and (almost) no instance of ERC20 include it. This means that you either:

- know for sure the contract implements ERC165, but then you also now for sure what the contract is, and that it is an ERC20 ...
- don't know the contract, and can't rely on ERC165 to detect if it is an ERC20

Going back in time, it would have been nice to have ERC165 before ERC20 (among a LOT of other things we would change about ERC20 is we were designing it today). However we have to work with the existing ecosystem, and given that ERC20 doesn't include 165, it makes very little sens to suddenly add it.

Note that if you want to add it, it should be very easy for you. We are just not going to make that choice for the user.

**Comment by TrejGun** [comment] 2022-07-26 08:57
@Amxx This would be a good start to make it a "best practice" to include supportsInterface into ERC20 if OZ does it.

**Comment by Pandapip1** [comment] 2022-08-05 18:00
> erc223

ERC-223 isn't a standard. It's not even merged into the EIPs repository. There's https://eips.ethereum.org/EIPS/eip-1363 (which is final and therefore safe to use) and there's https://eips.ethereum.org/EIPS/eip-4524.

**Comment by TrejGun** [comment] 2022-08-05 23:25
@Pandapip1 thanks for the heads-up! so far none of those are implemented, right? and it would be really nice to have one.

**Comment by Pandapip1** [comment] 2022-08-06 01:29
Yea, I would like to see an EIP-1363 implementation, but a new issue should be created for that.

**Comment by CJ42** [comment] 2023-04-06 02:42
@Amxx going back on this topic, I do still think it would make sense to add ERC165 by default in ERC20, so to advocate this as a best practice.

The most popular standard currently in effect are ERC20, ERC721 and ERC115, and the last two (721 & 1155) implement interface detection. It sounds non-standard and not conventional to not implement it on one of the three most used.

Especially as ERC20 is cited as one of the motivation behind the ERX165 standard itself.

Althought "supportsInterface" can always be faked (a dummy/malicious function implementation that can return "true" for certain interface IDs), it makes it more explicit. Otherwise it feels it's more "assumed".

I would be interested to hear @frangio opinion on this too.

![image](https://user-images.githubusercontent.com/31145285/230259047-ad52e2c4-d291-4f14-a71a-319e857b04ed.png)

**Comment by TrejGun** [comment] 2023-04-06 03:21
there is no downside of adding erc165 to erc20 however this may be superseded with upcoming merge of erc1363

**Comment by TrejGun** [comment] 2023-04-06 03:29
btw @Amxx do you have some kind of discord where I can contact you directly?

**Comment by hixbex7** [comment] 2023-04-06 03:40
Yes I do .... and I also have Gmail... ***@***.***

**Comment by Dexaran** [comment] 2023-08-25 12:56
>[ERC-223](https://github.com/ethereum/eips/issues/223) isn't an official standard. It's not even merged into the EIPs repository. There's https://eips.ethereum.org/EIPS/eip-1363 (which is final and therefore safe to use) and there's https://eips.ethereum.org/EIPS/eip-4524.

I would like to notify everyone that ERC-20 standard violates **common secure software design principles** ([source 1](https://kirkpatrickprice.com/blog/secure-coding-best-practices/) and [source 2](https://docs.oracle.com/en/operating-systems/oracle-linux/6/security/ol_desprinsc_sec.html)) that state:

1. **Error handling is a must.** In ERC-20 there is no transaction handling for `transfer` function which means error handling is impossible.
2. **Failsafe defaults / software must be secure by design.** ERC-20 is not secure by design and the "default" of `transfer` and `transferFrom` function is to allow action (transfer of tokens in this case) to be performed without checking for its correctness.
3. **Allowing the user to make decisions related to the internal logic of the program must be avoided**. Token transfers to EOAs and to contracts work differently. Secure token standard must determine the transferring method automatically. ERC-20, ERC-1363 and other token standards prompt a user to make a decision on what transferring method to use and if the wrong method was chosen - it results in the loss of tokens for the user.


What @Pandapip1 calls "safe to use" resulted in a loss of [$201,690,000 worth of tokens](https://gist.github.com/Dexaran/40213a04ce46b394279ac7daa581ce87). 

Here is a description thread: https://ethresear.ch/t/security-concerns-regarding-token-standards-and-130m-worth-of-erc20-tokens-loss-on-ethereum-mainnet/16387

Here is my old article on subject: https://dexaran820.medium.com/known-problems-of-erc20-token-standard-e98887b9532c#:~:text=ERC%2D20%20token%20standard%20contains,during%20the%20past%206%20years.

Here is another article that describes how `approve & transferFrom` pattern must be deprecated and considered insecure as well: https://dexaran820.medium.com/erc-20-approve-transferfrom-asset-transfer-method-poses-a-threat-to-users-funds-safety-ff7195127018

**As a security auditor I would not call something that resulted in a loss of $201M "safe to use".**

**Comment by Pandapip1** [comment] 2023-08-26 15:14
> What @Pandapip1 calls "safe to use" resulted in a loss of [$201,690,000 worth of tokens](https://gist.github.com/Dexaran/40213a04ce46b394279ac7daa581ce87).

Please provide a source for your quotation.

**Comment by Dexaran** [comment] 2023-08-26 17:27
@Pandapip1 

https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3575#issuecomment-1206710054

>https://github.com/ethereum/eips/issues/223 isn't an official standard. It's not even merged into the EIPs repository. There's https://eips.ethereum.org/EIPS/eip-1363 (which is final and therefore safe to use) and there's https://eips.ethereum.org/EIPS/eip-4524.

**Comment by Dexaran** [comment] 2023-08-26 17:39
|    | [ERC-223](https://eips.ethereum.org/EIPS/eip-223)   |  Ether    | [ERC-20](https://eips.ethereum.org/EIPS/eip-20)             | [ERC-721 (NFT)](https://eips.ethereum.org/EIPS/eip-721) | [ERC-777](https://eips.ethereum.org/EIPS/eip-777) | [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155) | [ERC-1363](https://eips.ethereum.org/EIPS/eip-1363) | [EOS C++ token](https://github.com/EOSIO/eosio.contracts/blob/master/contracts/eosio.token/src/eosio.token.cpp) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Push tx       | +             | +             | - | + | + | + | + | + |
| Pull tx   [(risky)](https://dexaran820.medium.com/erc-20-approve-transferfrom-asset-transfer-method-poses-a-threat-to-users-funds-safety-ff7195127018)    | -             | -             | + | + | + | + | + | - |
| Unhandled  [(insecure)](https://dexaran820.medium.com/known-problems-of-erc20-token-standard-e98887b9532c#:~:text=ERC%2D20%20token%20standard%20contains,during%20the%20past%206%20years.)   | -             | -             | + | - | + | - | + | - |
| Method by which the transacting method is selected (assuming that txs to EOAs and smart-contracts must be executed differently)   | Automated           | Automated             | User | User | User | User | User | Automated |

As you can see ERC-1363 inherits all the problems of ERC-20 that resulted in a loss of $200M.

**Comment by Pandapip1** [comment] 2023-08-27 15:54
Fair enough. I will edit that comment, as you are right, it is misleading. Consider that original statement retracted.

**Comment by frangio** [comment] 2023-08-30 01:23
I would add that an ERC being Final shouldn't be interpreted as it being safe, in general for any ERC.

---

Closing this issue for the reasons explained in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3575#issuecomment-1193764676.

**Closed by frangio** 2023-08-30 01:23 UTC
