### ISSUE TITLE
_isApprovedOrOwner vs. _isAuthorized

### ISSUE THREAD

**Issue by thomasender** [OpenZeppelin/openzeppelin-contracts#4844] opened 2024-01-18 11:38 UTC
According to documentation, ERC721.sol implements `_isApprovedOrOwner`, but according to Changelog `## 5.0.0 (2023-10-05)` It got removed in favor of `_isAuthorized` (to optimize SLOADs useage).  In the docs, `_isAuthorized` is not mentioned yet.

5.0.1

Please update the documentation

**Comment by ernestognw** [comment] 2024-01-18 15:09
Hey! The docs are in sync with the code, so [the documentation already includes `_isAuthorized`](https://docs.openzeppelin.com/contracts/5.x/api/token/erc721#ERC721-_isAuthorized-address-address-uint256-). Similarly, I couldn't find mentions to `_isApprovedOrOwner`.

This should be an easy update. Would you mind clarifyin the concrete changes to be made to the docs?

**Comment by ernestognw** [comment] 2024-01-24 16:04
Closing since it's unclear what the issue is.
We appreciate these heads up so feel free to reopen with the concrete changes require, just make sure the docs are those of 5.x and not 4.x.

**Closed by ernestognw** 2024-01-24 16:04 UTC
