### ISSUE TITLE
Contract ... is not upgrade safe

### ISSUE THREAD

**Issue by Zohar97** [OpenZeppelin/openzeppelin-contracts#5203] opened 2024-09-16 05:04 UTC
I'm using zksync-cli to create project and compile proxy contract which inherist **UUPSUpgradeable** and got this error:
Variable `__self` is assigned an initial value
    Move the assignment to the initializer
    
 Checking on UUPS lib, i see `address private immutable __self = address(this);`
 By checking OZ docs, i got "It is still ok to define constant state variables, because the compiler does not reserve a storage slot for these variables, and every occurrence is replaced by the respective constant expression. So the following still works with OpenZeppelin Upgrades:" but in this way, this __self variable is immutable, and it got warning from zksync deployment.
 
 What should i do?
 openzeppelin-contracts-upgradeable: 5.0.2

**Comment by Amxx** [comment] 2024-09-16 14:08
Hello @Zohar97 

This looks like a false positive from the zksync-cli. It looks like their system does not understand the use of an immutalbe variable that is shared by all proxy instances here.

**Comment by vmaark** [comment] 2024-09-18 12:37
@Zohar97 I ran into the same issue, it was caused by importing `Deployer` from `@matterlabs/hardhat-zksync` instead of `@matterlabs/hardhat-zksync-deploy` in my deploy script.

**Comment by Zohar97** [comment] 2024-09-19 04:51
> @Zohar97 I ran into the same issue, it was caused by importing `Deployer` from `@matterlabs/hardhat-zksync` instead of `@matterlabs/hardhat-zksync-deploy` in my deploy script.

i have try to import `Deployer` from `@matterlabs/hardhat-zksync-deploy` but got same issue

**Comment by cairoeth** [comment] 2024-10-27 11:55
closing as it's out of scope. reference: https://github.com/matter-labs/zksync-cli/issues/173

**Closed by cairoeth** 2024-10-27 11:55 UTC
