### ISSUE TITLE
ERC1155PresetMinterPauser: move grant role into an overridable function

### ISSUE THREAD

**Issue by peak3d** [OpenZeppelin/openzeppelin-contracts#2589] opened 2021-03-14 10:04 UTC
**🧐 Motivation**
We are using hardhat deterministic deploy and have to pass the correct owner in our ctor parameter.
msg.sender is in our case the deploy contract and should not get any roles.

rewoking 3 roles and after this _setup 3 roles cost lot of gas when deploying.

**📝 Details**

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/presets/ERC1155PresetMinterPauser.sol#L34-L37

Pls. either add an address _owner parameter in ctor, or move the 3 role  setups into an overridable function.

Thank you!!

**Comment by abcoathup** [comment] 2021-03-15 01:19
Duplicate of #2422

**Comment by abcoathup** [comment] 2021-03-15 01:21
Hi @peak3d!  Thanks for the suggestion, it is really appreciated.

I have marked this as a duplicate and will close this issue.

Please wait until we have discussed this idea before writing any code or submitting a Pull Request.  We don’t want you to waste your time!

**Closed by abcoathup** 2021-03-15 01:21 UTC

**Comment by peak3d** [comment] 2021-03-15 08:35
Thx @abcoathup !

**Comment by frangio** [comment] 2021-03-15 19:34
@peak3d I would recommend copying the `ERC1155PresetMinterPauser` contract (changing the relative import statements to be imports from our `@openzeppelin/contracts` package), and then making the change that you need.

**Comment by peak3d** [comment] 2021-03-15 20:46
Ok, sure that is possible. Not what we expected, but wi'll go this way. Thx!

**Comment by frangio** [comment] 2021-03-15 21:16
@peak3d The preset contracts are special in this regard because they just put together functionality, so they can serve as examples or templates.

**Comment by peak3d** [comment] 2021-03-16 07:41
Yes, understand! Much appreciate your quick response!
