### ISSUE TITLE
"Custom Error" .8.4

### ISSUE THREAD

**Issue by sandeepyadav1478** [OpenZeppelin/openzeppelin-contracts#2847] opened 2021-09-05 17:07 UTC
Getting Custom Errors log will emitting events. 

**💻 Environment**

Remix IDE

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by Amxx** [comment] 2021-09-06 08:10
duplicate of #2839

**Closed by Amxx** 2021-09-06 08:10 UTC
