### ISSUE TITLE
Implement a separate ERC721 and EIP2981 with the full and strict interface of EIP721

### ISSUE THREAD

**Issue by liron-navon** [OpenZeppelin/openzeppelin-contracts#3087] opened 2022-01-07 12:33 UTC
**🧐 Motivation**
The current ERC721 interface from openzepplin is deviating from the standard EIP721 interface, we need to make NFTs with royalties support, so we need functions like "safeTransferFrom" to be "payable". 

**📝 Details**
Open zepplin is missing some contract information to allow to create ERC721 that implement royalties, I'd like to suggest the implementation of the strict EIP721 as defined here: https://eips.ethereum.org/EIPS/eip-721
And the EIP2981 as defined here: https://eips.ethereum.org/EIPS/eip-2981

**Comment by Amxx** [comment] 2022-01-07 13:37
duplicate of #2610

**Closed by Amxx** 2022-01-07 13:37 UTC

**Comment by frangio** [comment] 2022-01-07 15:46
Note that ERC-2981 was merged yesterday (https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3012), it will be included in the next release.
