### ISSUE TITLE
[{ 	"resource": "/D:/NFT/contracts/MyNft.sol", 	"owner": "_generated_diagnostic_collection_name_#0", 	"code": "6275", 	"severity": 8, 	"message": "Source \"@openzeppelin/contracts/utils/counters.sol\" not found: File import callback not supported", 	"startLineNumber": 6, 	"startColumn": 1, 	"endLineNumber": 6, 	"endColumn": 53 }]

### ISSUE THREAD

**Issue by ajinkyablockchain** [OpenZeppelin/openzeppelin-contracts#5062] opened 2024-05-30 15:41 UTC
**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by ajinkyablockchain** [comment] 2024-05-30 15:42
code: //SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;


import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/counters.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contract/token/ERC721/extensions/ERC721URIStorage.sol";

contract MyNft is ERC721URIStorage, Ownable{
    
    using Counters for Counters.Counter;
    
    Counter.Counter private _tokenIds;
    constructor() ERC721("MY Nft","CRE"){}
    function mintnft(address recipient,string memory tokenURI)public onlyOwner returns(uint264){
      _tokenIds.increment();
    }

}

**Comment by cairoeth** [comment] 2024-05-31 18:28
Closing as it's duplicate of #5064.

**Closed by cairoeth** 2024-05-31 18:28 UTC
