### ISSUE TITLE
use block.timestamp instead of block.number for Governance contracts

### ISSUE THREAD

**Issue by z0r0z** [OpenZeppelin/openzeppelin-contracts#3353] opened 2022-04-24 12:32 UTC
**🧐 Motivation**
Improve cross-chain composability.

**📝 Details**
block.number -> .timestamp

**Comment by Amxx** [comment] 2022-04-24 13:20
Hello @z0r0z 

This is definitely something we are aware of, and concerned by:

https://twitter.com/amxx/status/1517413201067053056?t=gIIw6L9XIlFys2dQHXfCmg

Fixing it is hard, because it reaches into the tokens that are used for voting. We don't want a quick fix, we want something clean and safe. That will come, but it will take some time to get right.

**Comment by z0r0z** [comment] 2022-04-25 20:16
Thanks for the thoughtful response @Amxx

**Comment by frangio** [comment] 2022-05-04 21:18
Duplicate of #3081

**Closed by frangio** 2022-05-04 21:18 UTC
