### ISSUE TITLE
Recovery for EIP712 signed typed data

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-contracts#2073] opened 2020-01-30 22:15 UTC
**🧐 Motivation**
[EIP712](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md) has been around for quite some time, and is already on v4. Metamask has [support for it](https://metamask.github.io/metamask-docs/API_Reference/Signing_Data/Introduction), making it much more transparent for an end user to understand _what_ it is that they are signing. This recently came up as a request in the context of [signing GSN meta-txs](https://forum.openzeppelin.com/t/gsn-and-user-signatures/2176/1) (by user `ethicraul`), which greatly improves the UX of the signing request - to the point that [OpenEth is integrating this scheme into GSN v2](https://github.com/openeth-dev/gsn/commit/68772786f2eac1d79e2492c056cceb2507f3946b).

**📝 Details**
The current `ecrecover` library only provides support for hashing data into [the `Ethereum Signed Message` format](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/8975289c6b85caeedae815ebada00c6236a4ecce/contracts/cryptography/ECDSA.sol#L77-L81). We should add methods that simplify the verification of data signed with typed data v4. See [here](https://github.com/openeth-dev/gsn/commit/68772786f2eac1d79e2492c056cceb2507f3946b#diff-64f68efd4c88a36e1cb2ffafc39ace7eR96-R102) for the implementation built by OpenEth as an example, or [here](https://github.com/makerdao/dss/blob/44330065999621834b08de1edf3b962f6bbd74c6/src/dai.sol#L117-L141) for the implementation built into the DAI ERC20.

**Comment by frangio** [comment] 2020-01-31 13:28
This may be a duplicate of https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1810.

**Comment by frangio** [comment] 2021-08-06 01:26
I think this is resolved now since we have helpers for EIP712.

**Closed by frangio** 2021-08-06 01:26 UTC
Labels: feature, contracts
