### ISSUE TITLE
Checkpoints.History cause "out of gas" error

### ISSUE THREAD

**Issue by virgilea2410** [OpenZeppelin/openzeppelin-contracts#3974] opened 2023-01-19 11:20 UTC
Hello,

I am using a mapping of Checkpoints.History in my ERC1155-based contract to be able to know the balance of each user at a given block number.

For a unknown reason, the mint function, which calls the "push" function of Checkpoints.History, is periodically failing on "out of gas" error. 
While debugging, I can see it happens on the SSTORE operation on the line 144 of Checkpoints.sol

Here's my environment : 
- Remix 
- pragma solidity >=0.7.0

The mapping is defined as follow : 

mapping(uint256 => mapping(address => Checkpoints.History)) private balanceHistory;

And the mint function : 

// Mint Logic
    function _mintNFT(uint32 nMint, address recipient)
      internal
  {
      // require(tx.origin == msg.sender, "No bots allowed");
      require(totalSupply(currentTokenId) + nMint <= MAX_SUPPLY, "No more NFT to mint");
      require(waveCurrentSupply[currentTokenId] + nMint <= waveMintableSupply[currentTokenId], "No more NFT to mint for this wave");
      require(waveIsRunning[currentTokenId], "Wave has ended");
      waveBalance[currentTokenId] += msg.value;
      waveCurrentSupply[currentTokenId] += nMint;
      waveMints[currentTokenId][recipient] += nMint;
      // balanceHistory[currentTokenId][recipient].push(_add, nMint);
      balanceHistory[currentTokenId][recipient].push(balanceOf(recipient, currentTokenId) + nMint);
      _mint(recipient, currentTokenId, nMint, "");
  }

==> I tried both using push(op, value) and push(value)

**Comment by Amxx** [comment] 2023-01-19 12:44
Hello @virgilea2410 

The gas cost of pushing to `Checkpoints.History` is constant, so it should not be a blocker that would lock your contract. However, because the fact that checkpoints can sometimes overwritten might throw the gas prediction off.

Basically the gas prediction might think that the block number is the same, and that a dirty slot will be reused when the truth is that the tx will be in a new block, and that will require a new slot (which is more expensive)

In any case, it looks like the issue is not with the contract, but with the tooling used to call the contract.

**Comment by virgilea2410** [comment] 2023-01-19 13:02
@Amxx ,

Thanks a lot for the help.
I now understand where the problem is.

It was indeed my first idea (that the gas estimation was somehow wrong) but didn't think about the fact that block number would be different at gas estimation time VS runtime.

As far as you know, does it sounds normal to you that metamask is also wrongly estimating the gas (because saying that tx will probably succeed in less that 15sec), although when launching the tx with metamask, block number should be with a high probability the same that the one at runtime ? 
I would expect metamask to say "unknown delay" when estimating gas on its side

Also,

**Comment by Amxx** [comment] 2023-01-19 14:08
I'm not sure if metamask is the one doing the gas estimation, if its performed by the library that connects to metamask, or if its a matter of the node metamask connects to.

This is unfortunately a common issue. I encourage you to ask your question on the [openzeppelin forum](forum.openzeppelin.com/) where you may find users that have had, and fixed, this issue.

**Closed by Amxx** 2023-01-19 14:08 UTC

**Comment by frangio** [comment] 2023-01-19 18:58
Gas estimation may be assuming execution happens as part of the last minted block. If the last block has a checkpoint, the estimation will think that it can update that checkpoint but in fact the transaction will be included in the next block so it needs to create a new checkpoint, and the gas may not be enough for that because it's more expensive. Try waiting for a block to mine in between.
