### ISSUE TITLE
Infinite Gas

### ISSUE THREAD

**Issue by stebansaa** [OpenZeppelin/openzeppelin-contracts#4682] opened 2023-10-13 15:03 UTC
While using remix to deploy a erc20 or NFT, I see an infinite gas error on Remix

**💻 Environment**

Remix latest

**📝 Details**

Simply a infinite gas error, I had deployed countless times using OpenZepelling contracts generated form the wizard, first time I see this issue. Tried a few browsers. Is either related to the latest version of OpenZepellin contracts, or it could be the Remix IDE.

**Comment by ernestognw** [comment] 2023-10-13 19:50
Infinite gas errors are usually related to a contract reverting. 

Gas estimation is implemented as a binary search-based estimator, meaning that it'll try searching for the minimum amount of gas needed to get a successful execution, however, if the contract reverts the estimation results in infinity.

Having an error trace would be helpful to debug. I'm closing since Github issues are dedicated to discussions around OpenZeppelin Contract feature decisions, but you can ask for support in our [Community Forum](https://forum.openzeppelin.com/). Please include reproduction steps.

**Closed by ernestognw** 2023-10-13 19:50 UTC
