### ISSUE TITLE
SafeERC-20 incompatibility with Uniswap Liquidity Tokens 

### ISSUE THREAD

**Issue by jam10o-new** [OpenZeppelin/openzeppelin-contracts#1967] opened 2019-10-25 10:44 UTC
Due to the use of `abi.decode`, [which reverts on failure,](https://github.com/ethereum/solidity/issues/5902#issuecomment-458868819)  in SafeERC-20, successful Uniswap `transfer`s (which have a standard return value of true, but of non-standard size, apparently, perhaps a vyper bug) are reverted. 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/9e19d90cd9df3897e499753aa7951c0bc7759df7/contracts/token/ERC20/SafeERC20.sol#L72

This prevents Aragon orgs, for example, from allowing users to withdraw these tokens, [as I've bumped into here 😅](https://github.com/aragon/aragon-apps/issues/1028) 

Edit: this may just be a documentation issue - the previous description of `must equal true` is more accurate than the current description of `not false`. The most accurate description would be `must be a single truthy value` 😅.

**Comment by nventuro** [comment] 2019-10-25 16:30
Hm, interesting. Do you have a link to a failing transaction, so that we can take a look at what it is the token returns?

**Comment by joshua-mir** [comment] 2019-10-25 16:41
https://etherscan.io/vmtrace?txhash=0x8c421e96fb075fc165bf24511b803d7bbbb428034e46541a42015297f765aa2c&type=parity

**Comment by nventuro** [comment] 2019-10-25 18:51
I'm not being able to extract much useful information from that trace sadly :( From the Vyper code, it looks like `transfer` does indeed return a boolean type. Are those different from Solidity's?

**Comment by frangio** [comment] 2019-10-25 19:31
Thank you for reporting @joshua-mir.

If you could provide one, it would be very helpful to have a minimal project to reproduce this issue and debug it.

**Comment by abcoathup** [comment] 2020-01-31 05:57
Hi @joshua-mir,

Are you able to provide a minimal project to reproduce this issue and debug it?
Labeling as on hold.

**Comment by frangio** [comment] 2022-09-16 20:56
Closing due to lack of reproduction.

**Closed by frangio** 2022-09-16 20:56 UTC
Labels: on hold
