### ISSUE TITLE
Refactor ERC721 _operatorApprovals to an Internal Virtual Function 

### ISSUE THREAD

**Issue by Zer0dot** [OpenZeppelin/openzeppelin-contracts#2869] opened 2021-09-17 23:26 UTC
**🧐 Motivation**
Currently the only way to access `_operatorApprovals` in the [ERC721](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol) contract is via `setApprovalForAll()`, which is a public function that only sets operator approvals for the message sender.

I think it would be beneficial to refactor this into an internal virtual function that takes an additional `owner` parameter. This would allow expanded functionality such as a `permitForAll()` function, setting an operator approval via a meta-transaction. This also brings the flow closer to how `approve()` is handled.

**📝 Details**
Add a function to the ERC721 contract:
```
function _setOperatorApproval(address owner, address operator, bool approved) internal virtual {
    _operatorApprovals[owner][operator] = approved;
    emit ApprovalForAll(owner, operator, approved); 
}
```

Refactor the `setApprovalForAll()` function in the ERC721 contract:
```
function setApprovalForAll(address operator, bool approved) public virtual override {
    require(operator != _msgSender(), "ERC721: approve to caller");

    _setOperatorApproval(_msgSender(), operator, approved);
}
```
I think that's all it takes, let me know what you think!

**Comment by Amxx** [comment] 2021-09-19 12:56
Duplicate of #2832

**Closed by Amxx** 2021-09-19 12:56 UTC
