### ISSUE TITLE
[{ 	"resource": "/D:/NFT/contracts/MyNft.sol", 	"owner": "solidity-language-server", 	"code": "6275", 	"severity": 8, 	"message": "Source \"@openzeppelin/contracts/token/ERC721/ERC721.sol\" not found: File not found. Searched the following locations: \"\".", 	"source": "solidity", 	"startLineNumber": 5, 	"startColumn": 1, 	"endLineNumber": 5, 	"endColumn": 58 }]

### ISSUE THREAD

**Issue by ajinkyablockchain** [OpenZeppelin/openzeppelin-contracts#5061] opened 2024-05-30 15:41 UTC
**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

**Comment by cairoeth** [comment] 2024-05-31 18:28
Closing as it's duplicate of #5064.

**Closed by cairoeth** 2024-05-31 18:28 UTC
