### ISSUE TITLE
`ERC777._mint` should expose `requireReceptionAck` as function parameter in the same way that `_send` does or disable by default

### ISSUE THREAD

**Issue by SCBuergel** [OpenZeppelin/openzeppelin-contracts#2549] opened 2021-03-02 16:35 UTC
When implementing `mint` function of an ERC777 that simply calls the [internal `_mint` function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c789941d76dd713333bdeafe5b4484f6d9543c4e/contracts/token/ERC777/ERC777.sol#L307), currently one cannot opt out from the `requireReceptionAck` which is internally hard-coded to `true`. This is different from e.g. [`_send`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/c789941d76dd713333bdeafe5b4484f6d9543c4e/contracts/token/ERC777/ERC777.sol#L341). As a consequence, smart contracts (e.g. multisigs) cannot mint tokens for themselves, even when registered in the ERC1820 registry unless they implement the target function - but neither Gnosis Safe not Gnosis Wallet do implement that so it would be really useful to implement a `mint` function which disables the `requireReceptionAck` or pass `false` by default.

**Comment by abcoathup** [comment] 2021-03-02 23:39
Hi @SCBuergel!  Thanks for the suggestion, it is really appreciated.

Checking the EIP https://eips.ethereum.org/EIPS/eip-777#minting-tokens mint recipient contracts must implement the ERC777TokensRecipient
>The token contract MUST revert when minting in any of the following cases:
>
>The resulting recipient balance after the mint is not a multiple of the granularity defined by the token contract.
>The recipient is a contract, and it does not implement the ERC777TokensRecipient interface via ERC-1820.
>The address of the recipient is 0x0.
>The tokensReceived hook of the recipient reverts.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by frangio** [comment] 2021-03-03 00:32
Thank you for raising this @SCBuergel. This is actually a duplicate of https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2271. This is one of the things we want to resolve before we release the stable 4.0 version in about a week.

Closing as duplicate, please follow https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2271.

**Closed by frangio** 2021-03-03 00:32 UTC
