### ISSUE TITLE
Extending `balanceOf` function for the ERC20 smart contract.

### ISSUE THREAD

**Issue by ChinmayPatel** [OpenZeppelin/openzeppelin-contracts#2479] opened 2021-01-21 20:11 UTC
**🧐 Motivation**
Extending `balanceOf()` function for the purposes of manual calculation of balance.

**📝 Details**
It's not possible to `override` the [ERC20's `balanceOf` function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol) because it's not marked as virtual. How about marking it as both `overrider` and `virtual` so that we can extend the `balanceOf` functionality in the child contract. 

I'm currently using the 
* solidity version >=0.6.0 
* "@openzeppelin/contracts": "^3.3.0"

Thoughts?

**Comment by Amxx** [comment] 2021-01-21 20:33
Hello @ChinmayPatel, and thanks for raising this issue. I do believe that this was raised before by someone else in the community.

We are aware that having non-virtual function in our codebases limits the hability for developper like you to be creative with override. This is something that we are currently working on addressing.

We feel like the `balanceOf` function is a very sensitive one, and that overriding it might cause serious issues in the hability of users and Defi smart contracts to interract with your token. In particular, we are not sure how `transfer` should behave in such a case.

Could you tell use more about your usecase ? Are you doing balance rebasing ? How are you planning to override it and do you plan to override other functions as well ? We are really curious about our users usage of our contracts.

**Comment by ChinmayPatel** [comment] 2021-01-21 22:25
Thanks for the quick response. I completely agree with you that `balanceOf` is a very sensitive function. For now, I may simply fork the code and patch my updates, but this might be a handy feature for others, too.

For the use case, yes, you are right. We are trying to create a rebasing product. If you have any good reference implementations, I'm happy to look into them separately.

**Comment by abcoathup** [comment] 2021-01-22 02:48
Hi @ChinmayPatel,

Thanks for the feedback and sharing your use case.  I am closing this issue as making `balanceOf` `virtual` is covered in the below issue.  

Duplicate of https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154

**Closed** 2021-01-22 02:48 UTC
Labels: contracts, feature

**Comment by ChinmayPatel** [comment] 2021-01-22 13:49
Thanks @abcoathup . I'll follow #2154.

If you have any implementation reference on rebase tokens, can you please share a link or two?

**Comment by frangio** [comment] 2021-01-22 17:38
Here's an example, though we haven't reviewed it: [Ampleforth uFragments](https://github.com/ampleforth/uFragments/blob/master/contracts/UFragments.sol).
