### ISSUE TITLE
ERC-721 compliant `payable` functions

### ISSUE THREAD

**Issue by pcaversaccio** [OpenZeppelin/openzeppelin-contracts#3697] opened 2022-09-12 21:14 UTC
I have searched for a similar issue but have not found anything similar, so I open this issue for discussion.

In the official [EIP-721](https://eips.ethereum.org/EIPS/eip-721), the following functions are declared as `payable`:

```solidity
function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) external payable;
function safeTransferFrom(address _from, address _to, uint256 _tokenId) external payable;
function transferFrom(address _from, address _to, uint256 _tokenId) external payable;
function approve(address _approved, uint256 _tokenId) external payable;
```

The [OpenZeppelin interface definition](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/IERC721.sol) does not include the `payable` modifier. I assume there are some arguments against it from your side (e.g. prevent sending ETH to the contract without the possibility to retrieve it later etc.), but making the functions `payable` would of course save some gas and follow the EIP.

**Comment by frangio** [comment] 2022-09-13 17:41
Duplicate of https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2610.

See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2610#issuecomment-819006037.

**Closed by frangio** 2022-09-13 17:41 UTC
