### ISSUE TITLE
The assembly in mulDiv is not marked as memory safe

### ISSUE THREAD

**Issue by thedavidmeister** [OpenZeppelin/openzeppelin-contracts#4270] opened 2023-05-23 10:59 UTC
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/math/Math.sol

The `mulDiv` assembly is memory safe, but is not marked as such. This will cause the Solidity compiler to be more conservative than necessary when optimising code that includes `mulDiv`.

I don't have any data, but as `mulDiv` is fairly low level math, it's probably safe to assume it's included in a lot of contracts downstream and quietly breaking optimisations for people without them realising it.

https://docs.soliditylang.org/en/v0.8.13/assembly.html#memory-safety
https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3336

**Comment by PaulRBerg** [comment] 2023-05-24 10:41
This is correct. See this related discussion about PRBMath on the Solidity forum:

https://forum.soliditylang.org/t/understanding-the-memory-safe-dialect/1481?u=paulrberg

Nearly all `assembly` blocks in PRBMath are marked as memory safe:

https://github.com/PaulRBerg/prb-math/blob/97170d0f52de76edfb5fe63c5810a8705c3b0ea7/src/Common.sol#L387-L397

**Comment by PaulRBerg** [comment] 2023-05-24 13:42
It's not just that. Manipulation of reference-type variables outside of the inline assembly block could also be memory unsafe.

**Comment by thedavidmeister** [comment] 2023-05-24 13:55
@PaulRBerg only if those reference-type variables subsequently access 0x40-0x80, right?

**Comment by thedavidmeister** [comment] 2023-05-24 14:06
i really want to get this right... i have a lot of assembly code 😅

**Comment by frangio** [comment] 2023-05-29 21:31
At first glance, there are no memory operations at all within these assembly blocks so they are trivially memory safe. The Solidity documentation [indicates](https://docs.soliditylang.org/en/latest/assembly.html#memory-safety) that this does not turn off any optimizations:

> Therefore, moving stack variables to memory and additional memory optimizations are, by default, globally disabled in the presence of any inline assembly block that contains a memory operation or assigns to Solidity variables in memory.

This is also confirmed in the discussion linked by @PaulRBerg.

Should we still place the memory-safe annotations then? My intuition tells me no, because it unnecessarily introduces a possible error.

**Comment by PaulRBerg** [comment] 2023-05-30 08:51
I understand the potential for making errors, but without memory safe annotations, OpenZeppelin users will have a harder time verifying their contracts formally (e.g. with SMTChecker).

**Comment by thedavidmeister** [comment] 2023-05-30 12:05
actually i'm now confused by the solidity docs.. they say "access" a lot, without being clear about reads vs. writes.

reading the `0x40` would be "access" to memory in a region outside what is specified as safe to access, which would make it memory unsafe, but without reading/writing `0x40` it isn't possible to do what the docs say is "safe" allocation

that seems more like a question for solidity though

**Closed** 2023-05-31 20:33 UTC

**Comment by frangio** [comment] 2023-05-31 20:35
Got it. Closing this since the annotations are not necessary.
