### ISSUE TITLE
openzeppelin-contracts-upgradable: replace "if (A && B)" to save gas fees

### ISSUE THREAD

**Issue by BurtonQin** [OpenZeppelin/openzeppelin-contracts#4408] opened 2023-07-01 02:24 UTC
The solidity compiler generates more code for “if (A && B) {}” than for “if (A) {if (B) {} }”.
Our experiment shows that switching from “if (A && B) {}” to “if (A) {if (B) {} }” can save gas fee.

**💻 Environment**

master branch

**📝 Details**

Similar to issue [4404](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4404), there are nine such cases in openzeppelin-contracts-upgradable

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/utils/ArraysUpgradeable.sol#L45

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/token/ERC20/extensions/ERC4626Upgradeable.sol#L97

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/governance/extensions/GovernorPreventLateQuorumUpgradeable.sol#L69

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/governance/utils/VotesUpgradeable.sol#L203

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/governance/GovernorUpgradeable.sol#L200

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/access/AccessControlDefaultAdminRulesUpgradeable.sol#L121

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/token/ERC20/utils/SafeERC20Upgradeable.sol#L119

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/access/AccessControlDefaultAdminRulesUpgradeable.sol#L154

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/03b0aeb8e6b0badadbab83003c0456912fa06f89/contracts/utils/math/MathUpgradeable.sol#L218

**🔢 Code to reproduce bug**

**Comment by frangio** [comment] 2023-07-01 03:24
Duplicate of https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4404.

**Closed by frangio** 2023-07-01 03:24 UTC
